"""GlobalCLIP utils: models, datasets, training, and analysis."""

from .model import (
    GlobalCLIPStandardModel,
    GlobalCLIPQLayerModel,
    GlobalCLIPCNNModel,
    GlobalCLIPHybridModel,
    MixCoeffHead,
    QLayer,
)
from .datasets import GlobalCLIPDataset, build_dataloaders
from .training_utils import (
    GlobalCLIPLightningModule,
    pearson_loss,
    compute_log_enrichment,
    multinomial_nll_loss,
    save_run_config,
    load_run_config,
)
from .analysis_utils import (
    collect_alpha,
    rank_proteins,
    alpha_correlation_matrix,
    evaluate_pearson,
    evaluate_spearman,
    evaluate_pearson_windowed,
    evaluate_pearson_subset,
    NaiveBaselineModel,
    paired_significance,
    bootstrap_mean_diff_ci,
    plot_alpha_heatmap,
    plot_top_proteins,
    plot_phase_polar,
    plot_coupling_heatmap,
    plot_pearson_distribution,
)

__all__ = [
    "GlobalCLIPStandardModel",
    "GlobalCLIPQLayerModel",
    "GlobalCLIPCNNModel",
    "GlobalCLIPHybridModel",
    "MixCoeffHead",
    "QLayer",
    "GlobalCLIPDataset",
    "build_dataloaders",
    "GlobalCLIPLightningModule",
    "pearson_loss",
    "compute_log_enrichment",
    "multinomial_nll_loss",
    "save_run_config",
    "load_run_config",
    "collect_alpha",
    "rank_proteins",
    "alpha_correlation_matrix",
    "evaluate_pearson",
    "evaluate_spearman",
    "evaluate_pearson_windowed",
    "evaluate_pearson_subset",
    "NaiveBaselineModel",
    "paired_significance",
    "bootstrap_mean_diff_ci",
    "plot_alpha_heatmap",
    "plot_top_proteins",
    "plot_phase_polar",
    "plot_coupling_heatmap",
    "plot_pearson_distribution",
]
